import { siteConfig } from '@/config/site'
import { getPosts, getShorts } from '@/lib/fetchers'
import type { APIRoute } from 'astro'

export const GET: APIRoute = async () => {
  const posts = await getPosts()
  const shorts = await getShorts()

  const desc = [
    '# AnthonyZhu Personal Site',
    `> This is [my personal site](${siteConfig.url}),and it's built with \`astro\` and \`react\`.`,
    `> I will share some [technical blogs](${siteConfig.url}/post/) and [snippets of code and articles here](${siteConfig.url}/short/).`,
    '',
    `> [!TIP]`,
    `> The content on this website is all written by humans, not generated by AI.`,
    ''
  ]

  const postData = [`## Blog Posts`]
  posts.forEach(post => {
    postData.push(
      `- [${post.data.title}](${siteConfig.url}/post/${post.id}/): ${post.data.description}`
    )
  })

  const shortData = [`## Snippets of code and articles`]
  shorts.forEach(short => {
    shortData.push(
      `- [${short.data.title}](${siteConfig.url}/short/${short.id}/): ${short.data.description}`
    )
  })

  const otherPages = [
    `## Other Pages`,
    `- [Projects](${siteConfig.url}/projects/): Projects I've worked on, both ongoing and failed.`,
    `- [Uses](${siteConfig.url}/uses/): Tools I'm currently using, both hardware and software.`,
    `- [Now](${siteConfig.url}/now/): Here's what I'm currently working on.`,
    `- [Collective](${siteConfig.url}/collective/dev): I'll list my favorite developers here.`,
    `- [Credits](${siteConfig.url}/credits/): I've built this site with reference to other sites.`
  ]
  const optionPage = [
    `## Options`,
    `- [Source](${siteConfig.repoUrl}): This is the source code of my website, you can find everything about it here.`
  ]
  const markdown = [
    desc.join('\n'),
    postData.join('\n'),
    shortData.join('\n'),
    otherPages.join('\n'),
    optionPage.join('\n')
  ].join('\n\n')

  return new Response(markdown, {
    headers: {
      'content-type': 'text/plain;charset=utf-8'
    }
  })
}
